# Generated by Django 3.1.5 on 2021-01-31 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210131_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course'),
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file_url', models.FileField(upload_to='courseResources')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
            options={
                'verbose_name': 'CourseResources',
                'verbose_name_plural': 'CourseResourcess',
            },
        ),
    ]
