# Generated by Django 3.1.5 on 2021-02-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20210131_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Question it self')),
            ],
        ),
        migrations.CreateModel(
            name='Resolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=55, verbose_name='Your Problem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bulletinboard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-send_time', 'deadline', 'title']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-start_time', 'end_time', 'title']},
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.question')),
                ('resolve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.resolve')),
            ],
        ),
    ]
