# Generated by Django 3.1.5 on 2021-02-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20210204_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Resolve',
        ),
    ]
