# Generated by Django 3.1.5 on 2021-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210209_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('U', 'university_staff')], max_length=2),
        ),
    ]
