# Generated by Django 3.1.5 on 2021-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210209_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('U', 'university_staff')], default='S', max_length=2),
        ),
    ]
